### ISSUE TITLE
Action-Aliases `salt-local state.highstate` doesn't apply highstate

### ISSUE THREAD

**Issue by nzlosh** [StackStorm-Exchange/stackstorm-salt#15]
When the `salt.local` action is called from the command line providing `module=state.highstate` and `target`, the high state is applied to the target machine.  If the action is trigger via the action-alias, the result _appears_ to apply the configuration changes but none are observred on the target machine.  It seems like it's running with `test=true`.  

salt.local from action-alias
====================
```
id: 5defab2838b7e592a6f1332c
status: succeeded (5s elapsed)
parameters:
  args:
  - '[]'
  module: state.highstate
  target: automate*
result:
  exit_code: 0
  result:
```

salt.local from cli
=============
```
id: 5df0064c38b7e592a6f13347
status: succeeded (5s elapsed)
parameters:
  module: state.highstate
  target: automate*
result:
  exit_code: 0
  result:
```
The only difference I can see between the 2 calls is that `arg` parameter is passed an empty list.  This behaviour has been observed using salt-2018.3.4
